//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRoleMapping
    {
        public int MapId { get; set; }
        public int EmployeeId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
